apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app.kubernetes.io/name: aptos-extractor-coordinator
  name: aptos-extractor-coordinator
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aptos-extractor-coordinator
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aptos-extractor-coordinator
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      containers:
        - name: aptos-extractor-coordinator
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          env:
            - name: NODE_ADDRESS
              value: {{ .Values.env.node_address }}
            - name: FALLBACK_NODE_ADDRESS
              value: {{ .Values.env.fallback_node_address }}
            - name: GCP_PROJECT_ID
              value: {{ .Values.env.gcp_project_id }}
            - name: NETWORK
              value: {{ .Values.env.network }}
      restartPolicy: Always
