apiVersion: batch/v1
kind: Job
metadata:
  name: aptos-restore-job-mainnet-tornike
  namespace: mainnet
spec:
  template:
    spec:
      serviceAccountName: aptos-app-sa  # Specified service account name
      containers:
      - name: preload
        image: aptoslabs/tools:mainnet
        command: ["/bin/bash", "-c"]
        args:
          - |
            set -euxo pipefail
            mkdir -p /opt/aptos/etc/restore
            # Create backup.yaml
            cat <<EOF > /opt/aptos/etc/restore/backup.yaml
            env_vars:
            - key: BUCKET
              value: aptos-prod-mainnet-backups
            - key: SUB_DIR
              value: e1
            commands:
              create_backup: 'echo "\$BACKUP_NAME"'
              create_for_write: |
                FILE_HANDLE="\$BACKUP_HANDLE/\$FILE_NAME"
                echo "\$FILE_HANDLE"
                exec 1>&-  # close stdout
                gzip -c | gsutil -q cp - "gs://\$BUCKET/\$SUB_DIR/\$FILE_HANDLE" > /dev/null
              open_for_read: 'gsutil -q cp "gs://\$BUCKET/\$SUB_DIR/\$FILE_HANDLE" - | gzip -cd'
              save_metadata_line: |
                FILE_HANDLE="metadata/\$FILE_NAME"
                echo "\$FILE_HANDLE"
                exec 1>&-
                gzip -c | gsutil -q cp - "gs://\$BUCKET/\$SUB_DIR/\$FILE_HANDLE" > /dev/null
              list_metadata_files: '(gsutil -q ls gs://\$BUCKET/\$SUB_DIR/metadata/ ||:) | sed -ne "s#gs://.*/metadata/#metadata/#p"'
              backup_metadata_file: 'gsutil mv gs://\$BUCKET/\$SUB_DIR/metadata/\$FILE_NAME gs://\$BUCKET/\$SUB_DIR/metadata_backup/\$FILE_NAME'
            EOF
            # Cleanup aptosdb
            if [ -f /opt/aptos/data/restore-failed ] || \
                [ ! -f /opt/aptos/data/restore-uid ] || \
                [ "$(cat /opt/aptos/data/restore-uid)" != "" ]; then
              rm -rf /opt/aptos/data/db /opt/aptos/data/restore-{complete,failed}
              echo "" > /opt/aptos/data/restore-uid
            fi

            [ -f /opt/aptos/data/restore-complete ] && exit 0
            # Start restore process
            /usr/local/bin/aptos-debugger aptos-db restore bootstrap-db \
              --concurrent-downloads 16 \
              --target-db-dir /opt/aptos/data/db \
              --metadata-cache-dir /opt/aptos/data/aptos-restore-metadata \
              --ledger-history-start-version 0 \
              --command-adapter-config /opt/aptos/etc/restore/backup.yaml

            if [ $? -gt 0 ]; then
              # Mark restore as failed
              touch /opt/aptos/data/restore-failed
              exit 1
            else
              # Success, remove the marker
              rm -f /opt/aptos/data/restore-failed
              touch /opt/aptos/data/restore-complete
            fi
        volumeMounts:
        - name: aptos-config
          mountPath: /opt/aptos/etc
        - name: aptos-restore
          mountPath: /opt/aptos/etc/restore
        - name: aptos-genesis
          mountPath: /opt/aptos/genesis
        - name: aptos-data
          mountPath: /opt/aptos/data     
      restartPolicy: Never
      volumes:
      - name: aptos-config
        configMap:
          name: mainnet-aptos-fullnode
      - name: aptos-restore
        emptyDir: {}
      - name: aptos-genesis
        emptyDir: {}
      - name: aptos-data
        persistentVolumeClaim:
          claimName: mainnet-aptos-fullnode-e1
