apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod-with-volumes
  namespace: testnet
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/bash", "-c", "sleep 3600"]
    volumeMounts:
    - name: aptos-config
      mountPath: /opt/aptos/etc
    - name: aptos-restore
      mountPath: /opt/aptos/etc/restore
    - name: aptos-genesis
      mountPath: /opt/aptos/genesis
    - name: aptos-data
      mountPath: /opt/aptos/data
  restartPolicy: Never
  volumes:
  - name: aptos-config
    configMap:
      name: testnet-aptos-fullnode
  - name: aptos-restore
    emptyDir: {}
  - name: aptos-genesis
    emptyDir: {}
  - name: aptos-data
    persistentVolumeClaim:
      claimName: testnet-aptos-fullnode-e1
