environment: 
serviceAccountName: aptos-app-sa
GCPServiceAccountName: aptos-bq-prod-aptos-app@aptos-bq.iam.gserviceaccount.com

mainnet:
  replicaCount: 1
  namespace: mainnet
  env:
    node_address: http://mainnet-aptos-fullnode:8080/v1
    fallback_node_address: https://mainnet.aptoslabs.com/v1
    gcp_project_id: aptos-bq
    network: mainnet
  image:
    tag: aa84f6f

testnet:
  replicaCount: 1
  namespace: testnet
  env:
    node_address: https://testnet.aptoslabs.com/v1
    fallback_node_address: https://testnet.aptoslabs.com/v1
    gcp_project_id: aptos-bq
    network: testnet
  image:
    tag: aa84f6f
