# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pubsub_range.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'pubsub_range.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pubsub_range.proto\x12\x12\x61ptos.pubsub_range\"\xb4\x02\n\x0cTableOptions\x12\x13\n\x06\x62locks\x18\x01 \x01(\x08H\x00\x88\x01\x01\x12\x19\n\x0ctransactions\x18\x02 \x01(\x08H\x01\x88\x01\x01\x12\x13\n\x06\x65vents\x18\x03 \x01(\x08H\x02\x88\x01\x01\x12\x14\n\x07\x63hanges\x18\x04 \x01(\x08H\x03\x88\x01\x01\x12\x14\n\x07modules\x18\x05 \x01(\x08H\x04\x88\x01\x01\x12\x18\n\x0btable_items\x18\x06 \x01(\x08H\x05\x88\x01\x01\x12\x15\n\x08resource\x18\x07 \x01(\x08H\x06\x88\x01\x01\x12\x17\n\nsignatures\x18\x08 \x01(\x08H\x07\x88\x01\x01\x42\t\n\x07_blocksB\x0f\n\r_transactionsB\t\n\x07_eventsB\n\n\x08_changesB\n\n\x08_modulesB\x0e\n\x0c_table_itemsB\x0b\n\t_resourceB\r\n\x0b_signatures\"k\n\rIndexingRange\x12\r\n\x05start\x18\x01 \x01(\x04\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x04\x12\x34\n\x05table\x18\x03 \x01(\x0b\x32 .aptos.pubsub_range.TableOptionsH\x00\x88\x01\x01\x42\x08\n\x06_tableb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pubsub_range_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TABLEOPTIONS']._serialized_start=43
  _globals['_TABLEOPTIONS']._serialized_end=351
  _globals['_INDEXINGRANGE']._serialized_start=353
  _globals['_INDEXINGRANGE']._serialized_end=460
# @@protoc_insertion_point(module_scope)
