apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aptos-extractor-transformer-mainnet
  name: aptos-extractor-transformer-mainnet
  namespace: {{ .Values.mainnet.namespace }}
spec:
  selector:
    app.kubernetes.io/name: aptos-extractor-transformer-mainnet
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
    - name: "8080"
      port: 8020
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aptos-extractor-transformer-testnet
  name: aptos-extractor-transformer-testnet
  namespace: {{ .Values.testnet.namespace }}
spec:
  selector:
    app.kubernetes.io/name: aptos-extractor-transformer-testnet
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
    - name: "8080"
      port: 8020
      targetPort: 8080