apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: aptos-extractor-transformer
  name: aptos-extractor-transformer
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app.kubernetes.io/name: aptos-extractor-transformer
  ports:
    - name: "4000"
      port: 4000
      targetPort: 4000
    - name: "8080"
      port: 8020
      targetPort: 8080
